// Code generated by protoc-gen-tart. DO NOT EDIT. juice/v1/juice

import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:protobuf/protobuf.dart';
import 'package:tart/tart.dart' as twirp;
import 'juice.pb.dart';
import '../../summerfruits/v1/summerfruits.pb.dart';
import '../../google/protobuf/timestamp.pb.dart';



abstract class JuiceApi {
  
  Future<ListFlavoursResponse> listFlavours(
		twirp.Context ctx, 
		ListFlavoursRequest req,
	);
}


class JuiceApiJSONClient implements JuiceApi {
  String baseUrl;
  String prefix;
  late twirp.ClientHooks hooks;
  late twirp.Interceptor interceptor;

  JuiceApiJSONClient(this.baseUrl, this.prefix, {twirp.ClientHooks? hooks, twirp.Interceptor? interceptor}) {
    if (!baseUrl.endsWith('/')) baseUrl += '/';
    if (!prefix.endsWith('/')) prefix += '/';
    if (prefix.startsWith('/')) prefix = prefix.substring(1);

    this.hooks = hooks ?? twirp.ClientHooks();
    this.interceptor = interceptor ?? twirp.chainInterceptor([]);
  }

  @override
  Future<ListFlavoursResponse> listFlavours(
		twirp.Context ctx, 
		ListFlavoursRequest req,
		) async {
    ctx = twirp.withPackageName(ctx, 'v1');
    ctx = twirp.withServiceName(ctx, 'JuiceApi');
    ctx = twirp.withMethodName(ctx, 'ListFlavours');
    return interceptor((ctx, req) {
      return callListFlavours(ctx, req);
    })(ctx, req);
  }

  Future<ListFlavoursResponse> callListFlavours(twirp.Context ctx, ListFlavoursRequest req) async {
    try {
      Uri url = Uri.parse(baseUrl + prefix + 'juice.v1.JuiceApi/ListFlavours');
      final data = await doJSONRequest(ctx, url, hooks, req);
      final ListFlavoursResponse res = ListFlavoursResponse.create();
      res.mergeFromProto3Json(json.decode(data));
      return Future.value(res);
    } catch (e) {
      rethrow;
    }
  }
}


class JuiceApiProtobufClient implements JuiceApi {
  String baseUrl;
  String prefix;
  late twirp.ClientHooks hooks;
  late twirp.Interceptor interceptor;

  JuiceApiProtobufClient(this.baseUrl, this.prefix, {twirp.ClientHooks? hooks, twirp.Interceptor? interceptor}) {
    if (!baseUrl.endsWith('/')) baseUrl += '/';
    if (!prefix.endsWith('/')) prefix += '/';
    if (prefix.startsWith('/')) prefix = prefix.substring(1);

    this.hooks = hooks ?? twirp.ClientHooks();
    this.interceptor = interceptor ?? twirp.chainInterceptor([]);
  }

  @override
  Future<ListFlavoursResponse> listFlavours(twirp.Context ctx, ListFlavoursRequest req) async {
    ctx = twirp.withPackageName(ctx, 'v1');
    ctx = twirp.withServiceName(ctx, 'JuiceApi');
    ctx = twirp.withMethodName(ctx, 'ListFlavours');
    return interceptor((ctx, req) {
      return callListFlavours(ctx, req);
    })(ctx, req);
  }

  Future<ListFlavoursResponse> callListFlavours(twirp.Context ctx, ListFlavoursRequest req) async {
    try {
      Uri url = Uri.parse(baseUrl + prefix + 'juice.v1.JuiceApi/ListFlavours');
      final data = await doProtobufRequest(ctx, url, hooks, req);
      final ListFlavoursResponse res = ListFlavoursResponse.create();
      res.mergeFromBuffer(data);
      return Future.value(res);
    } catch (e) {
      rethrow;
    }
  }
}

Future<List<int>> doProtobufRequest(twirp.Context ctx, Uri url,
    twirp.ClientHooks hooks, GeneratedMessage msgReq) async {
  // setup http client
  final httpClient = http.Client();

  try {
    // create http request
    final req = createRequest(url, ctx, 'application/protobuf');

    // add request data to body
    req.bodyBytes = msgReq.writeToBuffer();

    // call onRequestPrepared hook for user to modify request
    ctx = hooks.onRequestPrepared(ctx, req);

    // send data
    final res = await httpClient.send(req);

    // if success, parse and return response
    if (res.statusCode == 200) {
      List<int> data = <int>[];
      await res.stream.listen((value) {
        data.addAll(value);
      }).asFuture();
      hooks.onResponseReceived(ctx);
      return Future.value(data);
    }

    // we received a twirp related error
    throw twirp.TwirpError.fromJson(
        json.decode(await res.stream.transform(utf8.decoder).join()), ctx);
  } on twirp.TwirpError catch (twirpErr) {
    hooks.onError(ctx, twirpErr);
    rethrow;
  } catch (e) {
    // catch http connection error or from onRequestPrepared
    final twirpErr = twirp.TwirpError.fromConnectionError(e.toString(), ctx);
    hooks.onError(ctx, twirpErr);
    throw twirpErr;
  } finally {
    httpClient.close();
  }
}

Future<String> doJSONRequest(twirp.Context ctx, Uri url,
    twirp.ClientHooks hooks, GeneratedMessage msgReq) async {
  // setup http client
  final httpClient = http.Client();

  try {
    // create http request
    final req = createRequest(url, ctx, 'application/json');

    // add request data to body
    req.body = json.encode(msgReq.toProto3Json());

    // call onRequestPrepared hook for user to modify request
    ctx = hooks.onRequestPrepared(ctx, req);

    // send data
    final res = await httpClient.send(req);

    // if success, parse and return response
    if (res.statusCode == 200) {
      final data = await res.stream.transform(utf8.decoder).join().then((data) {
        hooks.onResponseReceived(ctx);
        return data;
      });
      return Future.value(data);
    }

    // we received a twirp related error
    throw twirp.TwirpError.fromJson(
        json.decode(await res.stream.transform(utf8.decoder).join()), ctx);
  } on twirp.TwirpError catch (twirpErr) {
    hooks.onError(ctx, twirpErr);
    rethrow;
  } catch (e) {
    // catch http connection error or from onRequestPrepared
    final twirpErr = twirp.TwirpError.fromConnectionError(e.toString(), ctx);
    hooks.onError(ctx, twirpErr);
    throw twirpErr;
  } finally {
    httpClient.close();
  }
}

http.Request createRequest(
    Uri url, twirp.Context ctx, String applicationHeader) {
  // setup request
  final req = http.Request("POST", url);

  // add headers from context
  final headersFromCtx = twirp.retrieveHttpRequestHeaders(ctx) ?? {};
  req.headers.addAll(headersFromCtx);

  // add required headers
  req.headers['Accept'] = applicationHeader;
  req.headers['Content-Type'] = applicationHeader;

  return req;
}
